### ISSUE TITLE
Running without redis

### ISSUE THREAD

**Issue by liorsbg** [bekriebel/livekit-flydotio#4]
Thanks for this!

Is redis necessary if we're only running 1 instance?

**Comment by bekriebel** [comment]
You can run without redis, but it does affect reconnection. If a client gets disconnected for some reason like a temporary network interruption, they won't be able to reconnect automatically without redis backing the server. For this reason, I include it in the example.

There's an open ticket on livekit-server to resolve this. When that gets closed, I'll likely update this example to remove the redis component. You can follow that here: https://github.com/livekit/livekit-server/issues/83
